# Generated by Django 5.1.4 on 2025-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
