# Generated by Django 5.1.4 on 2025-01-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car1', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='CarMake_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car1.carmake'),
        ),
        migrations.AddField(
            model_name='car',
            name='CarMake_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car1.carmake'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
