# Generated by Django 5.1.4 on 2025-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car1', '0003_car_carmake_name_en_car_carmake_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='CarMake_name_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='CarMake_name_ru',
        ),
        migrations.AddField(
            model_name='car',
            name='car_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
